### PR TITLE
Unix mouse features

### PR DESCRIPTION
**Pull request by BDisp**

### CODE REVIEW

**Comment by BDisp** [comment]
@tig all done, but I hope it wouldn't to be always like that in the future because I'm start to stay desperate with the continuous rebase problems. It is takes me lost a lot of time.

**Comment by tig** [comment]
Are you still having those rebase issues? i had that one issue, but it seems to have been resolved.

**Comment by tig** [comment]
I merged this into my local fork and have been playing with it. 

You did something related to CTRL-Q handling such that in UI Catalog when you I am in a Scenario it often exits the whole app on CTRL-Q vs. just the scenario. If I press CTRL-Q *very* lightly/quickly it will do the right thing. It's like repeat sensitivity went way up. Do you have any idea why this might be? I thought I was going crazy so I `git checkout master` and tried again and it does not repro. So it's def something you did in this PR. This is on Windows!

I did a quick test where I changed UI Catalog to use CTRL-G in the `StatusBar` and that did not change anything. Note other than that, I do nothing special with CTRL-Q in the app.

**Comment by BDisp** [comment]
> 
> 
> Are you still having those rebase issues? i had that one issue, but it seems to have been resolved.

Yes I have, I always have a bunch of conflicts because my PR's aren't merged yet.

**Comment by tig** [comment]
Have you done a `git pull upstream master` into your local `master` and then `git merge master` into your local branches?

**Comment by tig** [comment]
> I merged this into my local fork and have been playing with it.
> 
> You did something related to CTRL-Q handling such that in UI Catalog when you I am in a Scenario it often exits the whole app on CTRL-Q vs. just the scenario. If I press CTRL-Q _very_ lightly/quickly it will do the right thing. It's like repeat sensitivity went way up. Do you have any idea why this might be? I thought I was going crazy so I `git checkout master` and tried again and it does not repro. So it's def something you did in this PR. This is on Windows!
> 
> I did a quick test where I changed UI Catalog to use CTRL-G in the `StatusBar` and that did not change anything. Note other than that, I do nothing special with CTRL-Q in the app.

I see `RequestStop` being called twice on every CTRL-Q. Hmmm....

**Comment by BDisp** [comment]
> 
> 
> Have you done a `git pull upstream master` into your local `master` and then `git merge master` into your local branches?

I did a fetch upstream master then rebase my local branch onto upstream master and then I rebase the local branches with rebase onto my local master. I do all this with the git in vs2019.

**Comment by BDisp** [comment]
> I see `RequestStop` being called twice on every CTRL-Q. Hmmm....

That should be the reason of the issue.

**Comment by BDisp** [comment]
And it's all for today. Good work.

**Comment by tig** [comment]
I found it:

					if (inputEvent.KeyEvent.bKeyDown) {
						// Key Down - Fire KeyDown Event and KeyStroke (ProcessKey) Event
						keyHandler (new KeyEvent (map));
						keyDownHandler (new KeyEvent (map));
					} else {
						// Key Up - Fire KeyDown Event and KeyStroke (ProcessKey) Event
						keyHandler (new KeyEvent (map));
						keyUpHandler (new KeyEvent (map));
					}

Should be:

					if (inputEvent.KeyEvent.bKeyDown) {
						// Key Down - Fire KeyDown Event and KeyStroke (ProcessKey) Event
						keyHandler (new KeyEvent (map));
						keyDownHandler (new KeyEvent (map));
					} else {
						keyUpHandler (new KeyEvent (map));
					}

Cheers and good night!

**Comment by tig** [comment]
I found it. it was caused, likely by a manual merge you had to do. I'm sorry you had such difficulty.

				if (inputEvent.KeyEvent.bKeyDown) {
						// Key Down - Fire KeyDown Event and KeyStroke (ProcessKey) Event
						keyHandler (new KeyEvent (map));
						keyDownHandler (new KeyEvent (map));
					} else {
						keyUpHandler (new KeyEvent (map));
					}

should be

					if (inputEvent.KeyEvent.bKeyDown) {
						// Key Down - Fire KeyDown Event and KeyStroke (ProcessKey) Event
						keyHandler (new KeyEvent (map));
						keyDownHandler (new KeyEvent (map));
					} else {
						keyUpHandler (new KeyEvent (map));
					}

Cheers & good night!

**Comment by tig** [comment]
I accepted this PR and then did another (`fix_pr489`) to fix this little issue.

**Pull request merged**
