### PR TITLE
Allowing negative coordinates for scrolling purpose.

### PR DESCRIPTION
**Pull request by BDisp**
I also made the smaller ScrollView functional.

### CODE REVIEW

**Comment by BDisp** [comment]
> 
> 
> I don't like the complexity of adding a 'force' parameter to 'Move'.
> 
> Are you certain there's not another way to support this without changing the `Move` public API?

You're right. Done!

**Comment by tig** [comment]
Ya gotta rebase. Sorry about that.

**Comment by BDisp** [comment]
I already did it.
`"This branch is even with migueldeicaza:master. "`

**Comment by tig** [comment]
But if I look at the changed files, that doesn't jive...

image

**Comment by BDisp** [comment]
@tig was it you who did not rebase?

**Comment by tig** [comment]
> @tig was it you who did not rebase?

This is the last PR that was merged to master is this one, earlier today: https://github.com/migueldeicaza/gui.cs/pull/673

It is clean.

image

**Comment by BDisp** [comment]
You do you explain this. I have the same last commit as yours.

bdisp-gui-cs

**Comment by tig** [comment]
Weird. I don't understand. 59faa66..60d714c is the current master.

**Comment by BDisp** [comment]
This is my story.

history

**Comment by tig** [comment]
What happens if you do 

   git checkout master
   git pull upstream master
   git checkout negative-coordinates
   git merge master
   git push --set-upstream origin negative-coordinates

**Comment by BDisp** [comment]
Instead of `git merge master` I was doing `git rebase master`. I always used `rebase `to the PR branches. What is the difference?

**Pull request merged**
