### PR TITLE
New control: Popup menu

### PR DESCRIPTION
**Pull request by Slesa**
New Control: Popup menu (#15)
Problem is the hiding of the menu after ESC - it takes a second to redraw the screen. It also has probably too much source code in common with menu.cs.

Open questions:
- Should the menu be closed after clicking on the rest of the screen?
- Should the menu be closed after the action of an item is executed? 
  Here, the popup could also be a main menu where you call different submodules - as the example shows:
   Call the setup part, return to menu
   Call the maintenance part, return to menu
   All done, quit the menu and exit the application

### CODE REVIEW

**Comment by migueldeicaza** [comment]
Answers: 

* I think that we should close the popup menu if the user clicks outside of the menu
* I think that after the action is triggered, it should hide the menu

**Comment by Slesa** [comment]
I don't think it should close automatically after the action is triggered. If it does not, you can build a small tool which (e.g. a Starter tool for other programs) which simply draws an initial popup menu in the center of the screen, which has submenus also drawn as popup menus. Which means: if you open a submenu and close the main menu after triggering, the submenu has no root window.

**Comment by migueldeicaza** [comment]
I think that nested menus should be first class citizens, so activating a submenu does not close the menu, but beyond that, the action would make sense.

**Comment by tig** [comment]
This is an old/stale PR. I'm closing it due to lack of activity.

@Slesa, if you would be so kind, please submit another PR with this change as having Popup menus (per #206) would be awesome!

**Pull request closed without merging**
