### PR TITLE
Date/TimeField - Added features stated in #475 and  #246

### PR DESCRIPTION
**Pull request by BDisp**
It's depend on the PR #488

### CODE REVIEW

**Comment by tig** [comment]
Looks like you need to merge this with another of your PRs as it's failing:

 Views/TimeField.cs(98,14): error CS0103: The name 'ReadOnly' does not exist in the current context [/home/vsts/work/1/s/Terminal.Gui/Terminal.Gui.csproj]

**Comment by BDisp** [comment]
I already merged it.

**Comment by tig** [comment]
BDDisp, I don't think this is ready. 

- Layout still doesn't work (Calculated or Absolute).
- The TimeDate Scenario causes crashes easy.

I'll push an update to UI Catalog with a repro asap.

I think we should agree that any new functionality checked in to this project must have a `Scenario` in `UI Catalog` that sufficiently exercises it.

**Comment by BDisp** [comment]
I'll see it. Remember that you can't force the width because they are fixed to be stay centered in the text field.

**Comment by BDisp** [comment]
I just verified that you already implemented it in the same way as my PR. Do you want it to close?

**Comment by tig** [comment]
> I just verified that you already implemented it in the same way as my PR. Do you want it to close?

Not sure what you mean. Can you elaborate?

**Pull request closed without merging**
