### PR TITLE
Feature/status bar

### PR DESCRIPTION
**Pull request by Slesa**
First try for a StatusBar (#9). It uses the same layout as the MenuBar. 
Includes the fix of the build (#200) to be able to compile.

### CODE REVIEW

**Comment by migueldeicaza** [comment]
This looks good - would you be so kind in adding inline API docs, so folks can figure out how to use this?

**Comment by Slesa** [comment]
I was not sure if you would like it. 
Next plan would be to show the help texts of the menu in such a statusbar, but draw the hotkey of a menu item after its text. As there is no event system, there may could be a static member StatusBar.Current to draw a message after the items. 

The problem is - I'd need my other commits of the menu system ;) I have too many PRs here.

**Comment by migueldeicaza** [comment]
@BDisp  Do we still need this patch, now that we merged the other branch?

**Comment by BDisp** [comment]
I think it's not needed now. But @Slesa had the merits of this.

**Comment by Slesa** [comment]
Well, if it is not needed anymore...

**Comment by migueldeicaza** [comment]
Thank you folks!

**Pull request closed without merging**
