### PR TITLE
Resolves Button Text Alignment with Unicode chars.

### PR DESCRIPTION
**Pull request by BDisp**

### CODE REVIEW

**Comment by tig** [comment]
Please rebase first.

**Comment by BDisp** [comment]
Please wait a while, as there will be changes to this PR. Thank you.

**Comment by BDisp** [comment]
Sorry @tig but I am having some difficulties in finding a common algorithm to properly handle justified alignment. If you want to merge what's already in order to be able to advance any, you can do it. As soon as this matter is resolved, I will re-submit PR. Thanks.

**Comment by BDisp** [comment]
Not yet but I will of course. Please see the changes and tell me something please. Thanks.

**Comment by BDisp** [comment]
Damn my vs2019 is inserting using without asking, like this `System.Net.Sockets`. Sorry.

**Comment by BDisp** [comment]
@tig I think that is all merged.

**Comment by BDisp** [comment]
Only  `DimPosTests.TestPercent() line 112` has error.

**Comment by BDisp** [comment]
Comma instead of period. I think that is about the `CurrentCulture`.

**Pull request merged**
