### PR TITLE
Added a OpenSelectedItem event to the ListView #429

### PR DESCRIPTION
**Pull request by BDisp**

### CODE REVIEW

**Comment by tig** [comment]
I've tested this with `UI Catalog` and it works wonderfully. Really nice work! Thanks.

**Comment by BDisp** [comment]
Usage example:

```
private static void ListView_OpenSelectedItem (object sender, EventArgs e)
{
	var item = ((ListView)sender).SelectedItem;
	var itemName = ((ListView)sender).Source.ToList ();
	MessageBox.Query (50, 7, "Selected Item is: ", $"{item}:{itemName[item]}", "Ok");
}

```

**Comment by BDisp** [comment]
In agreement and subscribing to what @tig mentioned in #447, I present the respective changes to the pending ListView PR. Now, by invoking any of these events, the desired values ​​in the '`e`' argument can be obtained directly.

```
private static void ListView_SelectedChanged (object sender, ListViewItemEventArgs e)
{
	MessageBox.Query (50, 7, "Selected Item is: ", $"{e.Item}:{e.Value}", "Ok");
}

private static void ListView_OpenSelectedItem (object sender, ListViewItemEventArgs e)
{
	MessageBox.Query (50, 7, "Selected Item is: ", $"{e.Item}:{e.Value}", "Ok");
}

```

**Comment by migueldeicaza** [comment]
I love the change - a conflict came up after some recent merges, can we fix this, and then merge?

**Comment by BDisp** [comment]
Ok after all the merges are done I'll fixes them.

**Pull request closed without merging**
