### PR TITLE
Fixes #1133. Flaw in LayoutSubviews/TopologicalSort.

### LINKED ISSUE #1133: Flaw in LayoutSubviews/TopologicalSort
Hello,

I just realized that the code in LayoutSubviews that collects the dependencies is incomplete:

```
                        foreach (var v in InternalSubviews) {
                                nodes.Add (v);
                                if (v.LayoutStyle == LayoutStyle.Computed) {
                                        if (v.X is Pos.PosView vX)
                                                edges.Add ((vX.Target, v));
                                        if (v.Y is Pos.PosView vY)
                                                edges.Add ((vY.Target, v));
                                        if (v.Width is Dim.DimView vWidth)
                                                edges.Add ((vWidth.Target, v));
                                        if (v.Height is Dim.DimView vHeight)
                                                edges.Add ((vHeight.Target, v));
                                }
                        }
```

The issue is that this is not taking into account the Dim and Pos subclasses that combine two views, so we only do the proper job of topologically sorting when there is a direct dependency, not when there is something like view + 1 (when we create a combined pos/dim)

The code needs to handle PosCombine/DimCombine and recursively add the elements to it.

### PR DESCRIPTION
**Pull request by BDisp**

### CODE REVIEW

**Comment by BDisp** [comment]
I should receive an alert with PR conflicts.

**Comment by tig** [comment]
> I should received an alert with PR conflicts. But I don't received nothing.

I don't understand.

**Comment by BDisp** [comment]
> 
> 
> > I should received an alert with PR conflicts. But I don't received nothing.
> 
> I don't understand.

This PR had a conflict because the MessageBox scenario was also changed on another PR, but I didn't received an email alerting this conflict. By chance I opened the PR browser and noticed that there was conflict.

**Comment by tig** [comment]
> > > I should received an alert with PR conflicts. But I don't received nothing.
> > 
> > 
> > I don't understand.
> 
> This PR had a conflict because the MessageBox scenario was also changed on another PR, but I didn't received an email alerting this conflict. By chance I opened the PR browser and noticed that there was conflict.

got it. so everything is ok now? 

Can I merge this? (I am still reviewing it).

**Comment by BDisp** [comment]
Wait, I'll do a check.

**Comment by BDisp** [comment]
Sorry @tig. It's all alright.

**Comment by BDisp** [comment]
@tig, after all, my suspicions that something was not yet well, was confirmed. `Application.Top` has to be excluded from `TopologicalSort` method verification because it is the basis of all views.

**Comment by BDisp** [comment]
@tig sorry for all this disturbance. I hope the solution is your liking. Thanks.

**Pull request closed without merging**
