### PR TITLE
Fixes #703 Label layout issue.

### LINKED ISSUE #703: Layout issue in the Label.
In my opinion I think that the `LayoutSubviews ()` method should not be virtual because it is essential for the redisposition of all views and any overriden may forget to call the base. But for now I just put the Label to call the base method. What is your opinion?

layout-issue

### PR DESCRIPTION
**Pull request by BDisp**

### CODE REVIEW

**Comment by tig** [comment]
suggest you pull down my #702 first. You'll see this is already fixed because Label no longer has any code in it. I think.

**Comment by BDisp** [comment]
I will. Thanks.

**Comment by BDisp** [comment]
Closing this because @tig  suggestion is better. Thanks.

**Comment by BDisp** [comment]
> 
> 
> suggest you pull down my #702 first. You'll see this is already fixed because Label no longer has any code in it. I think.

Confirmed. Thank you.

**Pull request closed without merging**
