### PR TITLE
Wide runes console fix

### LINKED ISSUE #1673: Message Box Rune Support Erroneous
**Describe the bug**
As of version 1.5.0, the `MessageBox` still seems to take issues with runes. Something similar was recently report in issue #1657 (with a PR to solve this in PR #1658). Then again there was also issue #1665 (context menu width) which subsequently got solved in PR #1666. I think a similar bug fix is required for the `MessageBox` class.

Here's a summary of the current state of message box:

| language | `-usc` | result                                                                                            |
|-----------|--------|----------------------------------------------------------------------|
| `en_US`   | `false`  | works as expected                                                                       |
| `en_US`   | `true`   | invisible message box                                                                  |
| `ja_JP`      | `false` |  works but the alignment of the message box message is off    |
| `ja_JP`      | `true`  | invisible message box                                                                  |

**To Reproduce**
I noticed this behavior on the application I am currently working on (https://github.com/StefanGreve/dtui/tree/chatview). To reproduce this bug you can run this application with `dtui.exe run --langauge [en_US|ja_JP] -usc`. Try to log in (login method is not implemented yet, so any combinations of strings would do the trick) and cancel the process by clicking on the `[ cancel ]` button to trigger the message box.

**Expected behavior**
The message box should be visible (notice that it is still possible to exit the message box form with the now invisible `ok` button). Also the Japanese text (and likely any other text which contains runes) should not be cut off. In the GIF below, the text is not really centered when the language profile is set to Japanese.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 10
 - Version 10.0.19044

**Additional context**
This behavior was observed on CMD, PowerShell and Windows Terminal with always the same outcome. The example in the GIF was run on Windows PowerShell.

### PR DESCRIPTION
**Pull request by BDisp**
All drivers are rendering well on the Windows Terminal for wide runes.
Fixes #1673

### CODE REVIEW

**Comment by tig** [comment]
What do I need to fix in the `Character Map` Scenario to fix it now that you've done this?

image

**Comment by BDisp** [comment]
I almost already have the `Character Map` also corrected on `Windows Terminal` but for that I will submit a pull request to the `NStack` repo, before it is really possible. I am just trying to deal with some different behaviors between `WindowsDriver` and `CursesDriver`.

**Comment by tig** [comment]
> I almost already have the `Character Map` also corrected on `Windows Terminal` but for that I will submit a pull request to the `NStack` repo, before it is really possible. I am just trying to deal with some different behaviors between `WindowsDriver` and `CursesDriver`.

Should I wait to approve this PR until that's done? Or are they really separate issues?

**Comment by BDisp** [comment]
When I have this PR ready it can be approved even before the PR that I will submit to the NStack is approved, but the necessary corrections can only be visible after the correction is merged in the NStack and published to Nuget.

**Comment by BDisp** [comment]
I hope @migueldeicaza could merge my pr https://github.com/migueldeicaza/NStack/pull/57 to this working better.

**Comment by migueldeicaza** [comment]
I'll check it out soon!

**Comment by BDisp** [comment]
@tig you need rerun the actions because it's a false fail build.

**Pull request merged**
