### PR TITLE
Feature/MenuItemSeparator

### PR DESCRIPTION
**Pull request by Slesa**
Fixing menu item separator (#192)

- do not crash when item is null
- when using cursor, do not activate line if item is empty
- use the right color scheme

### CODE REVIEW

**Comment by migueldeicaza** [comment]
I defined it already for null to be a separator, would that work for you?

**Comment by kbilsted** [comment]
@migueldeicaza  You are incorrect. If using `null` it crashes  `Menu.MakeFrame()` see PR #304

**Comment by BDisp** [comment]
@kbilsted sorry but you aren't totally correct. @migueldeicaza in my pr #298 the menu separator is working well. See the demo in File menu. I used some code of the @Slesa pr #202 and some more coding to make it work. Disabled menu item is working well too.

**Comment by kbilsted** [comment]
@bdisp please explain how I am wrong.

**Comment by BDisp** [comment]
@kbilsted you said if using null it crashes Menu.MakeFrame() and in my pr #298 I use null to create a menu separator without crashing.

**Comment by tig** [comment]
The `UI Catalog` "Editor" Scenario clearly demonstrates menu item separators are working. Closing this.

image

**Pull request closed without merging**
