### PR TITLE
A provisional solution to the #1065 issue. Setting HeightAsBuffer as true by default.

### PR DESCRIPTION
**Pull request by BDisp**

### CODE REVIEW

**Comment by BDisp** [comment]
@tig I think this PR improves `WindowsDriver `a little more than it is right now. Please check when you have time. Thanks.

**Comment by tig** [comment]
I just tested this and I don't think it is right.

At some point Terminal.Gui with WidnowsDriver sized correctly and worked fine on all consoles I used on Windows (cmd.exe, VS debug, Windows Terminal, and ConEmu). Somewhere along the line a change was introduced which broke this. 

Trying to calculate the size of the console by asking for the console font used is going to be very error-prone. The current PR doesn't work correctly. 

Windows Terminal:
(sometimes it is right, but only if the window is sized just right)
image

cmd.exe:
image

Conemu:
image

VS Debug:
image

What was the change that broke this? @BDisp do you know precisely what changed that broke this?

**Comment by BDisp** [comment]
> @BDisp can you back that commit out? What else will break if you do?

@tig this is still not in perfect working order but I think it is better than it is currently. Removing this commit will stop the console's resizing and the vertical scroll bar will always appear on the console. In my opinion we will have to take the font size into account when calculating the size although it can sometimes be erroneous, but it will be better than using fixed constants. If someone more knowledgeable about the `Windows Native APIs` could help, that would be great. In my opinion if we want to have the possibility of having the console resized without always appearing the vertical scroll bar, we could merge this PR and wait for a solution, because the console can work as it used to do if we set `HeightAsBuffer` to true.

**Comment by tig** [comment]
> > @BDisp can you back that commit out? What else will break if you do?
> 
> @tig this is still not in perfect working order but I think it is better than it is currently. Removing this commit will stop the console's resizing and the vertical scroll bar will always appear on the console. In my opinion we will have to take the font size into account when calculating the size although it can sometimes be erroneous, but it will be better than using fixed constants. If someone more knowledgeable about the `Windows Native APIs` could help, that would be great. In my opinion if we want to have the possibility of having the console resized without always appearing the vertical scroll bar, we could merge this PR and wait for a solution, because the console can work as it used to do if we set `HeightAsBuffer` to true.

Every Windows console calculates font sizes differently. There is no way to ask the various consoles how they calculate font size. Thus it will be impossible to make Terminal.Gui always work on all consoles this way. I think living with the vertical scroll bar is a far better solution. 

Previously resizing the console horizontally (shrinking or growing) worked well. 

Vertical resizing worked for growing but not shrinking, except on ConEmu which worked both ways. This means it is possible for consoles to do the right thing. We may never get VS debug or cmd.exe to do the right thing, but I'm willing to bet we can convince the Windows Terminal team to do what Conemu does.

**Comment by tig** [comment]
Thank you!

**Pull request merged**
