### PR TITLE
Fixes some DateField and TimeField bugs.

### PR DESCRIPTION
**Pull request by BDisp**

### CODE REVIEW

**Comment by BDisp** [comment]
@tig If you merge this PR you will see that the problem of the TimeAndDate.cs scenario will solved. The problem is that it is using absolute values ​​and computed at the same time. As the PR already has new constructors to receive only the value of the date and time is resolved.

**Comment by BDisp** [comment]
It seems that DateTime does not handle the various date formats well when switching from long format to short format so I will have to create my own patch for that purpose. If, however, you are able to solve it in another way, please tell me.

**Comment by tig** [comment]
> It seems that DateTime does not handle the various date formats well when switching from long format to short format so I will have to create my own patch for that purpose. If, however, you are able to solve it in another way, please tell me.

Building a control that handles all date/time formats is a Hard problem. I did it in native Windows back in the '90s and it was a BITCH.

**Comment by BDisp** [comment]
I'll try to tame it :-)

**Comment by BDisp** [comment]
Problem solved. You can merge now if you want. PR #524

**Comment by BDisp** [comment]
> 
> 
> It seems that DateTime does not handle the various date formats well when switching from long format to short format so I will have to create my own patch for that purpose. If, however, you are able to solve it in another way, please tell me.

Solved with PR #524

**Pull request merged**
