### PR TITLE
ComboBox cursonDownKey nullref fix

### PR DESCRIPTION
**Pull request by En3Tho**
A small fix for https://github.com/migueldeicaza/gui.cs/issues/1471
Added null guard to fix null ref when pressing keyDown inside combobox
Improved an error message when view cannot be found

### CODE REVIEW

**Comment by En3Tho** [comment]
@tznind @BDisp Is this suitable fix for the problem or should it be done another way?

**Comment by tznind** [comment]
Thanks! @tig handles PR review but this looks fine to me.  Are you able to add a unit test?

**Comment by En3Tho** [comment]
Okay, So I've found a few bugs with a unit test. Please look at them. Hontesly can we just make search set not null all the time? Is one allocation worth it?

**Comment by BDisp** [comment]
I think is better avoiding null list. It must be an empty list on these cases.

**Comment by BDisp** [comment]
Another solution to make possible to insert ComboBox on a smaller superview is to add the ListView to the superview's Superview, instead added to the ComboBox.

**Comment by tznind** [comment]
I agree with both of you, empty list is good.  Lets solve the simple null reference issue first then look at a different PR for bigger changes?

**Comment by BDisp** [comment]
@En3Tho don't forget that the searchset is a new source based on filtering what is tipping. If TextField is empty then all the source elements are shown.

**Comment by En3Tho** [comment]
Yeah, but if you set TextField initially, then it is not actually empty and this behaviour skips searchset initialization resulting in a null ref

**Review by tig — APPROVED** [review]
LGTM!

**Pull request merged**
