### PR TITLE
Added wheeling feature to the ScrollView.

### PR DESCRIPTION
**Pull request by BDisp**

### CODE REVIEW

**Comment by BDisp** [comment]
What is happening with gui? I can't rebase the master.

**Comment by BDisp** [comment]
I had to delete all my repository and push all again. What the hell.

**Comment by BDisp** [comment]
Why it's giving this error? I did not' changing anything related with Net version.

```
/opt/hostedtoolcache/dncs/3.1.101/x64/sdk/3.1.101/Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.7.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/runner/work/gui.cs/gui.cs/Example/Example.csproj]
/opt/hostedtoolcache/dncs/3.1.101/x64/sdk/3.1.101/Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.7.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/runner/work/gui.cs/gui.cs/Designer/Designer.csproj]
/opt/hostedtoolcache/dncs/3.1.101/x64/sdk/3.1.101/Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.7.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/runner/work/gui.cs/gui.cs/Terminal.Gui/Terminal.Gui.csproj]
    21 Warning(s)
    3 Error(s)
```

**Comment by tig** [comment]
Delete your obj directories and try again.

**Comment by BDisp** [comment]
It's nothing about building but the error when I submitted this PR and previous I compared my master with the @migueldeicaza master and it was even with it. But after that error my master was 11 behind commits and I couldn't rebase the master because of an owner's error.

**Comment by tig** [comment]
Weird.

**Comment by tig** [comment]
FWIW, I just had an issue where I could not `git checkout master` when I had `fix_ui_catalog` checked out. It said I had untracked changes, but there were none. I tried everything. I eventually had to re-enlist! WTF?

**Comment by BDisp** [comment]
It was really weird. Before deleting the merged branches I usually rebase the origin/master with the upstream/master and then rebase the branches that have not yet been merged. When I submitted this PR there was an error in the build on Github. I went to compare the masters again and they were not synchronized. Thus, this sometimes which becomes very discouraging.

**Comment by BDisp** [comment]
Again the same error:
```

`
Error encountered while pushing to the remote repository: rejected master -> master (refusing to allow an OAuth App to create or update workflow `.github/workflows/dotnetcore.yml` without `workflow` scope)

```
@tig this happens evertime after you do a merge in the @migueldeicaza master and then when I attempt to do a rebase.

**Comment by BDisp** [comment]
Deleting git in windows credentials and login in Github again solved for now, but I had to delete my repository and fork again to rebase the master accordingly :-(

**Pull request merged**
