### PR TITLE
ListView support both LayoutStyle to calculate the height.

### LINKED ISSUE #772: ListView does not have the correct height when set the SelectedItem.

### PR DESCRIPTION
**Pull request by BDisp**
Instead of the `top `being set when the `SelectedItem `property is changed it is calculated before being drawn.

Fixes #772

### CODE REVIEW

**Comment by BDisp** [comment]
When the `SelectedItem `is assigned he will check if he has to move the items by comparing the height. The problem is that if the `LayoutStyle `is `Computed`, the ListView does not have this information and in this case, only when it is going to draw the control does it already have that information. So I created the `topPendent `flag to force it to calculate the width.

**Comment by tig** [comment]
Do you know when ListView started moving the selected item to the top when SelectedItem changed?

I'm not a fan of this behavior and am not sure if it's related to this PR or not. 

`SelectedItem.set` should only change the scroll position of the list box to display the selected item if it was not previously visible. Anything otherwise is disruptive to the UI. See my comment on the other PR for an example.

**Comment by BDisp** [comment]
> Do you know when ListView started moving the selected item to the top when SelectedItem changed?

Do not know. I've always seen him like this but I really shouldn't. Thanks for the clarification.

> Anything otherwise is disruptive to the UI. See my comment on the other PR for an example.

Where?

**Comment by BDisp** [comment]
Of course, when the `ListView `already contains a `SelectedItem `whose index is higher than the height, the selected item must appear at the top. Note that this only happens when you assign a value to `SelectedItem.set` or by scrolling with `PageUp`, `PageDown`, `Home `and `End`.

**Comment by tig** [comment]
> > Do you know when ListView started moving the selected item to the top when SelectedItem changed?
> 
> Do not know. I've always seen him like this but I really shouldn't. Thanks for the clarification.
> 
> > Anything otherwise is disruptive to the UI. See my comment on the other PR for an example.
> 
> Where? I think is this [#765 (comment)](https://github.com/migueldeicaza/gui.cs/pull/765#issuecomment-655652695)

Correct.

Do you know how to fix that issue? Can it be fixed as part of this PR?

**Comment by BDisp** [comment]
I'll merge PR #765 in this one and you'll see.

**Comment by BDisp** [comment]
Done!

**Comment by BDisp** [comment]
I sent the separate PRs for you not to complain. I should have sent it along ;-)

**Comment by BDisp** [comment]
> `SelectedItem.set` should only change the scroll position of the list box to display the selected item if it was not previously visible.

I think this is already fixed.

**Pull request merged**
