### PR TITLE
Faster handling of the mouse in ScrollView with the addition of an uninterrupted click on the mouse features. Changed the Wakeup method to reset the events to update the screen.

### PR DESCRIPTION
**Pull request by BDisp**

### CODE REVIEW

**Comment by migueldeicaza** [comment]
Beautiful!

**Comment by tig** [comment]
I think this broke this: https://github.com/migueldeicaza/gui.cs/pull/208.

Or, I'm doing something wrong. The progress bars do not update unless I move the mouse around:

```csharp
		private void Pulse ()
		{
			if (_activityProgressBar.Fraction + 0.01F >= 1) {
				_activityProgressBar.Fraction = 0F;
			} else {
				_activityProgressBar.Fraction += 0.01F;
			}
			_pulseProgressBar.Pulse ();
			
		}

		private void Start ()
		{
			if (_timer != null) {
				_timer.Dispose ();
				_timer = null;
			}

			_activityProgressBar.Fraction = 0F;
			_pulseProgressBar.Fraction = 0F;

			_timer = new Timer ((o) => Application.MainLoop.Invoke (() => Pulse ()), null, 0, 250);
		}

		private void Stop ()
		{
			if (_timer != null) {
				_timer.Dispose ();
				_timer = null;
			}

			_activityProgressBar.Fraction = 1F;
			_pulseProgressBar.Fraction = 1F;
		}
```

**Comment by BDisp** [comment]
I'll check that but is strange because I already fixed before.

**Comment by tig** [comment]
FWIW, I don't get automatic updates when I run under Linux either. Am I doing something wrong in my code above?

**Comment by BDisp** [comment]
To work in WSL I think the fixes are in PR #435

**Comment by tig** [comment]
This is still broken. The `Progress` example in #501 demonstrates this for me using BOTH `WindowsDriver.cs` and `CursesDriver.cs`:

**Comment by BDisp** [comment]
With this sample it will work
https://github.com/migueldeicaza/gui.cs/pull/501#issuecomment-632962091

**Pull request merged**
