### PR TITLE
bugfix null as menu separator

### PR DESCRIPTION
**Pull request by kbilsted**
Support menu items that are null so they can be drawn as a menu separator

### CODE REVIEW

**Comment by BDisp** [comment]
@kbilsted you should present a demonstration of what you are correcting

**Comment by BDisp** [comment]
@kbilsted in my pr #298 the menu separator is working well. See the demo in File menu.

**Comment by BDisp** [comment]
@kbilsted sorry but you aren't totally correct. @migueldeicaza in my pr #298 the menu separator is working well. See the demo in File menu. I used some code of the @Slesa pr #202 and some more coding to make it work. Disabled menu item is working well too.

**Comment by kbilsted** [comment]
This is a simple nullreference bugfix, not sure what you are on about

**Comment by BDisp** [comment]
@kbilsted I know what you are talking about. You mean about the code in @migueldeicaza that doesn't parse if the items parameter is null. But if you do checkout of some very good pr's, and I'm not talking about mine, you would find that many of the flaws that still exist, will be resolved as it is just waiting for a good review by @migueldeicaza. So @Slesa pr # 202 solved the problem if items is null. If you notice the code that I used and that by mistake I didn't mention pr # 202 in my pr is the following code that solves this problem in another way.

		static Rect MakeFrame (int x, int y, MenuItem [] items)
		{
			int maxW = 0;

			foreach (var item in items) {
				if (item == null) continue;
				var l = item.Width;
				maxW = Math.Max (l, maxW);
			}

			return new Rect (x, y, maxW + 2, items.Length + 2);
		}

**Comment by kbilsted** [comment]
I have seen your approaches. I think my approach is more maintainable.

**Comment by BDisp** [comment]
@kbilsted of course your approach is more maintainable. I didn't say it wasn't. I just warned you to first check all pull-requests in the repository, test them, merge them if they are useful, and then improve them. Because you don't want to just rely on the master and invent the whole wheel again. I hope you understand that I am not criticizing you but just asking you to take a look at pr's first. Don't get me wrong please :)

**Comment by kbilsted** [comment]
@BDisp Help me out here. Why are you advertising merging in PRs you yourself identify to be less optimal than this PR. How will that benefit the code base? In my book it won't benefit anything.

ps. I'm not trying to "hit you".

**Comment by BDisp** [comment]
@kbilsted I know it's not hitting, there's no problem. Really as I just said the cursor has always been and is still visible in the original repository and even helps me control the flow of the program. I just had to worry about creating color schemes for two situations I needed, for the menu and text selected through the mouse. Believe me the elaboration of the submenus has given me a hard time. For now, I can't dwell on that but if you present something integrated into the view class or a derivation the effect would be more widespread than just a demo application that would only be used to demonstrate library functionality.

**Comment by kbilsted** [comment]
@migueldeicaza  what is the forecast to merge a simple null-fix PR? ;)

**Comment by migueldeicaza** [comment]
Thank you for your contribution!

**Pull request merged**
