### PR TITLE
Fixes issue #306 async/await hang

### PR DESCRIPTION
**Pull request by BDisp**

### CODE REVIEW

**Comment by BDisp** [comment]
> 
> 
> [a683345](https://github.com/migueldeicaza/gui.cs/commit/a68334551098b3d97ffffd41771aee8c2f002375)
> @timothyparez is the last one. I think it must always be the last. Someone said that changes submitted to an already submitted PR can always be done on the same PR. However, I had a doubt that I would be grateful if someone with true knowledge of the subject please clarify me. Must the changes be submitted based on the last submission, as it really was, or will I have to make the changes again from a new upstream/master checkout? Thanks in advance.

I put a question on https://github.com/migueldeicaza/gui.cs/issues/306#issuecomment-558539249 regarding this PR and although I am waiting for a reply by someone well understood on this subject, I reflected and I am forward with this my following opinion. I really think we should only merge the upstream because there may have been new commited merged from uptream after the last PR and then resubmitting the new changes. By the way, if there have been changes in the upstream and submit without merging first does git warn you before or not?

**Comment by timothyparez** [comment]
@BDisp I have no idea. I mostly use Gitlab (hosted and on-premise) because Github is blocked every other day here.

**Comment by BDisp** [comment]
The question is for anyone who might be able to answer me correctly. Anyway thanks

**Comment by timothyparez** [comment]
@BDisp so I checked out your latest. 
The weird behavior persists.

**Comment by BDisp** [comment]
@migueldeicaza can you help me with this CI error, please. In my travis all went well with no errors was you can see below:
travis

In your travis I got errors with nuget unsigned packages as you can see below:
yourtravis

 After merged with your master I also started receiving the same errors as yours. Looks like you might have to update some nuget packages for CI to stop giving errors.

**Comment by migueldeicaza** [comment]
Thank you for your contribution!

**Pull request merged**
