### PR TITLE
Making ListView.ListWrapper public #313

### PR DESCRIPTION
**Pull request by timothyparez**

### CODE REVIEW

**Comment by kbilsted** [comment]
I would prefer moving it out so it is no longer an inner class :-)

**Comment by timothyparez** [comment]
> 
> 
> I would prefer moving it out so it is no longer an inner class :-)

That would be even better yes, I do not like nested classes.    
Not sure what the original reasoning behind it was.   
I'll take a look in the morning if it would break anything.

**Comment by kbilsted** [comment]
It won't

**Comment by BDisp** [comment]
@timothyparez, I was already working on this change :).
As @kbilsted stated it is better to move outside the ListView class to avoit the "Do not nest ListWrapper type. Alternatively, change its accessibility so that it is not externally visible."
Also I had prepare a litle change to ListView to allow setting SetSource async. If you want to add to include your PR, better.

```
		/// <summary>
		/// Sets the source to an IList value asynchronously, if you want to set a full IListDataSource, use the Source property.
		/// </summary>
		/// <value>An item implementing the IList interface.</value>
		public Task SetSourceAsync (IList source)
		{
			return Task.Factory.StartNew (() => {
				if (source == null)
					Source = null;
				else
					Source = MakeWrapper (source);
				return source;
			}, CancellationToken.None, TaskCreationOptions.DenyChildAttach, TaskScheduler.Default);
		}

```

**Comment by timothyparez** [comment]
@BDisp It should be ok now.
Currently I just moved it to ListWrapper.cs but since it is not a `View`,  
should we move it to a separate folder and what should we name it?

**Comment by timothyparez** [comment]
Azure pipelines failed but I can't see why.

**Comment by BDisp** [comment]
You could leave it in the same file it was before because it belong to ListView. See in the travis about the error

**Comment by timothyparez** [comment]
I always stick to the one class per file rule.

**Comment by BDisp** [comment]
> 
> 
> I always stick to the one class per file rule.

Me too. But in others' houses we have to respect the rules I think. If you look at the Menu.cs file you will find that there are four classes and only two are derived from View, because the author thought that as it was referring to the same subject decided to keep everything in the same file. In these cases it even looks good and is very common. If I were to decide, I would keep it in the same file but outside the ListView class. But it's up to you, of course. But the biggest problem is that you are submitting your PR through your master. I've done it before :)

**Comment by timothyparez** [comment]
Let me follow @BDisp's advice and I will create a new PR later.

**Pull request closed without merging**
