### PR TITLE
Fixes Windows Terminal initial resize on CursesDriver related with #1768.

### PR DESCRIPTION
**Pull request by BDisp**
It wasn't clearing at `CursesDriver` initialization.

### CODE REVIEW

**Comment by BDisp** [comment]
Should `ResizeScreen` method be made abstract?

**Comment by BDisp** [comment]
> Should `ResizeScreen` method be made abstract?

@tig, @tznind what your opinion about this?

**Comment by BDisp** [comment]
CursesDriver was the one that used this method before and now it's using I thinking is better made as abstract and override in each derived class.

**Comment by BDisp** [comment]
> I don't see a problem with doing that. What is your concern?

I'll do it then. Thanks.

**Review by tig — APPROVED** [review]
Nice.

**Pull request merged**
