### PR TITLE
Resizing the MessageBox width to accommodate all message text

### PR DESCRIPTION
**Pull request by BDisp**

### CODE REVIEW

**Comment by BDisp** [comment]
@kbilsted try File-> Open and you will find that keys events are not processed due to the break instruction in the if (topLevel.Modal)

**Comment by kbilsted** [comment]
Sounds like a different problem that the subject of the PR

**Comment by BDisp** [comment]
@kbilsted you are right. It was a problem that was solved by merging pr # 288 'fixed-key-events-traversal-for-modal-dialogs'

**Comment by kbilsted** [comment]
Uaually for a PR to get acceptes easily it holds only one change/fix not several unrelated changes

**Comment by BDisp** [comment]
@kbilsted as you know, because you even got my attention, all changes, merges and writing new codes have always been done in my master branch and always with the same pr. Really, I was wrong, and when trying to create new branches for new submissions, I lost the topic in some transitions. Anyone who wants to check all my code is fully updated on my fork if something has escaped me. There also often happened to be conflict when merge some pr and I changed it according to what I found best for the repository. I think I will make the rules from now on, but it was only due to some ignorance. Don't hit me please :)

**Comment by kbilsted** [comment]
I'm not hitting you. I'm not the maintainer of this repo, so I don't know how PR's are preferred here. If I was the maintainer, I would not appreciate mixing everything together.

**Comment by BDisp** [comment]
@kbilsted you are not hitting me, but you are always repeating me for the wrong way I put my PR's in, even though I have already admitted them and apologized for it, but you insist on repeating them again. I'm not a maintainer of this repository either, nor do I know how public relations is preferred here. All I hope is that the maintainer is not as overwhelming as you. Of course, the maintainer has already caught my attention and asked me to relocate the PRs separately. If you spent a little time checking the comments you would notice this call from the maintainer.

**Comment by biohazard999** [comment]
@BDisp @kbilsted be nice to each other! Not everyone is used to work in the open. And esp if you are new to open source, it's sometimes hard to get into it. @BDisp did a great job the last days (or even weeks i dunno) in trying to contribute. Not everyone is perfect. @kbilsted I'll get your point, I wouldn't accept some PR's either (cause they seam a bittle random sometimes). But if you are on fire on a project, then it can get messy really quick. But that's the point of having PR's after all.

**Comment by kbilsted** [comment]
@biohazard999 +1 completely agree. 

Out of curiosity,  at what point do you think my comments were personal or condescending?

**Comment by biohazard999** [comment]
@kbilsted I don't think your comments were neither personal nor condescending. It's more they are a little unhappy expressed and could be more [constructive, helpful and precise](https://www.insightsforprofessionals.com/management/leadership/art-of-giving-feedback). 

> Why do you change ProcessKeyEvent() ?
> Can you make a test to show that the calculations are more correct ?

could be for example:
What`s your idea behind changing the `ProcessKeyEvent`? 
I don't understand the change or is this something that just slipped in?
If possible, please provide a sample or test that justifies the change.

I worked a lot in the last time in the [open](https://github.com/Code52/pretzel/pulls?q=is%3Apr+is%3Aclosed+author%3Abiohazard999) and asking questions is a lot better, than demanding.

In this way, I believe misunderstandings can be avoided :) 

Do you understand my point of view/"criticism"?

**Comment by kbilsted** [comment]
@biohazard999 On multiple occasions I've clearly expressed I don't have the intention of "hitting" anyone.  And having a terse style of writing should *not* necessitate a smiley face at the end of every sentence.

Perhaps you can share a few links on the psychology if going into open source and sharing your code (which to some is a very personal thing). Perhaps the core of the problem is not the writer needing a lecture on how to write more precise. Certainly I'm not the party who is getting all worked up. 
In that light its a bit puzzling you telling me to be nice to others when you have no indications of me being not-nice? 

:-)

**Comment by biohazard999** [comment]
@kbilsted 
> In that light its a bit puzzling you telling me to be nice to others when you have no indications of me being not-nice?
I hoped that It made this point clear with `comments were neither personal nor condescending`.
You don't seam to be a mean person, by no means! 

I agree, not every comment needs to end with an emoji, we are adults after all. So we should be also able to act professional. 

> Perhaps you can share a few links on the psychology if going into open source and sharing your code (which to some is a very personal thing). 
I don't have any links by hand right now. But if I find some interesting ones, I'll post them.

> Perhaps the core of the problem is not the writer needing a lecture on how to write more precise. Certainly I'm not the party who is getting all worked up.
I'm not sure what you are refering to. I follow this repo for a long time now, and you two had a hard argument. I just want to relax the conversation a little bit.

**Comment by migueldeicaza** [comment]
Thank you for your contribution!

**Pull request merged**
