### PR TITLE
Added F11 and F12 keys #220. Changed keyDownHandler to before keyHandler.

### PR DESCRIPTION
**Pull request by BDisp**

### CODE REVIEW

**Comment by BDisp** [comment]
Fixes this too https://github.com/migueldeicaza/gui.cs/issues/531#issuecomment-633222935

**Comment by tig** [comment]
Nice!

**Comment by tig** [comment]
Did you mean to break the `ESC-C` == `ALT-C` functionality here?

**Comment by BDisp** [comment]
My intention there was just to handle the TAB key. If I broke it, I don't know. If so, I'm sorry.

**Pull request merged**
