### PR TITLE
New Control 'TableView' for viewing tabular data

### PR DESCRIPTION
**Pull request by tznind**
Hey,

I have been using your awesome framework for a while and wanted to contribute.  I have written a control for #255 .  I have reviewed the contribution guidelines and code of conduct.

I have added a new `Scenario` and tested it in Windows and MXLinux.

- The control works with `System.DataTable`
   - I thought that would be a good way to avoid parsing CSVs as well as supporting viewing results from relational databases etc
- Columns autosize based on the column widths and the widths of the **visible** cells
- Supports horizontal and vertical scrolling including PageUp/Down/Home/End
- User can configure 
  - Maximum cell width
  - How to represent nulls
  - What character to use as a column separator (defaults to space)

Currently when you change the contents of the `Table` or the `ColumnOffset` or `SelectedColumn` you will also have to call `Update` before it will re-render.  This lets the API user drop columns or make many changes to the `System.DataTable` without having to respond to every one.  But it could also be confusing if the user changes the `SelectedRow` and doesn't see the UI immediately update.

image

Let me know if there are inefficiencies in the `Redraw`.  I noticed that the `HexView` (which I based this on) has a local method `SetAttribute` which I kept... although I'm not using it.

I'm unsure about the guidline (any guidance on how to do that would be great please):
> Ensure the UICatalog demo for the new class illustrates both Absolutle Layout and Computed Layout.

Currently the control doesn't explicitly handle newlines in cell values but those seem to be replaced by spaces in DrawString anyway.

### CODE REVIEW

**Comment by BDisp** [comment]
It looks good, thanks.



> I'm unsure about the guidline (any guidance on how to do that would be great please):
> 
> > Ensure the UICatalog demo for the new class illustrates both Absolutle Layout and Computed Layout.

See the `Button` `Update `method on how to change the `Width`. If it isn't null or an absolute value you must use the necessary code to change his `Width `and `Height` based on their type, unless that a control have a specific `Width `or `Height`, like the case of the `Button` `Height `is always equal to `1` where you must save the state of the `LayoutStyle `before changing his value and restore to the original `LayoutStyle `value. If a view have it's `Layout Style.Computed` the position and size depends on other views and changing to an absolute value causes the views stop to be anchored.

**Comment by BDisp** [comment]
Don't forget to add documentation to the "`Missing XML comment`" warnings.

**Comment by BDisp** [comment]
If you aren't use the `SetAttribute `you can remove because already exist a `ColorScheme `property in the base class `View`.

**Comment by tznind** [comment]
Thanks, now that I look again at `Redraw` I think I am confusing `bounds` and `Frame`.  I think all my size calculations (what columns to render where) should be done solely on `Frame` is that right?

**Comment by BDisp** [comment]
> Thanks, I will add comments and tidy up pointless variables. Now that I look again at `Redraw` I think I am confusing `bounds` and `Frame`. I think all my size calculations (what columns to render where) should be done solely on `Frame` is that right?

`Bounds `is related to the position and size of own view. `Frame `is related to the position and size in the screen. Only the size is equal on both. So in general it's only needed to deal with the `Bounds `property from `0` to `Bounds.Width` and `0` to `Bounds.Height` and the `View `class will deal with the convertion from view position to screen position. But there are some situations where you need to deal with the `Frame `property to check some positions and size against the windows size to take some actions needed.

**Comment by tznind** [comment]
> 
> 
> > Thanks, I will add comments and tidy up pointless variables. Now that I look again at `Redraw` I think I am confusing `bounds` and `Frame`. I think all my size calculations (what columns to render where) should be done solely on `Frame` is that right?
> 
> `Bounds `is related to the position and size of own view. `Frame `is related to the position and size in the screen. Only the size is equal on both. So in general it's only needed to deal with the `Bounds `property from `0` to `Bounds.Width` and `0` to `Bounds.Height` and the `View `class will deal with the convertion from view position to screen position. But there are some situations where you need to deal with the `Frame `property to check some positions and size against the windows size to take some actions needed.

Ok Cool thanks for that explanation, then I will leave it how it is for now.

**Comment by tig** [comment]
I'll try to take a close look at this asap because I think it's gonna be awesome. I will see if I can re-write `out-consolegridview` to use this instead of the hacky way it simulates a table view today!

**Comment by migueldeicaza** [comment]
Hello,

Is System.Data.DataTable available on .NET Core and .NET Standard?   

One thing that might be good to do with this view is to support the rendering similar to what Spectre.Console has, allowing users to set borders for example:

https://www.hanselman.com/blog/spectreconsole-lets-you-make-beautiful-console-apps-with-net-core

**Comment by tznind** [comment]
> Hello,
> 
> Is System.Data.DataTable available on .NET Core and .NET Standard?
> 

Hi, thanks for taking the time to look at this PR.  Yes it was in dotnet core 1.0 (Dotnet Standard 2.0 onwards)

https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable?view=net-5.0#applies-to

> One thing that might be good to do with this view is to support the rendering similar to what Spectre.Console has, allowing users to set borders for example:
> 
> https://www.hanselman.com/blog/spectreconsole-lets-you-make-beautiful-console-apps-with-net-core

Thanks for pointing me there they look awesome.  I have added table border lines and toggles for them in UICatalog.

image

**Comment by BDisp** [comment]
Great job, thanks. Perhaps it may be implemented cells alignment.

**Comment by tznind** [comment]
> Great job, thanks. Perhaps it may be implemented cells alignment.

Thanks, I have added a `ColumnStyle` class so that some columns can have different widths, alignment,formats  etc.

image

See method `SetDemoTableStyles()` in UICatalog for example of how to configure them.  I also added a menu item to the Scenario that clears the styles.

**Comment by migueldeicaza** [comment]
Wow, this is looking fantastic!

In the DoubleCol screenshot, I imagine that this can be aligned right, and that I can also specify the formatting options?

**Comment by tznind** [comment]
> 
> 
> Wow, this is looking fantastic!

Thanks!

> In the DoubleCol screenshot, I imagine that this can be aligned right, and that I can also specify the formatting options?

Yes, you can either specify a fixed alignment for the col:

```csharp
Alignment = TextAlignment.Right,
```

Or you can assign alignment based on the values (e.g. negative values aligned right, positive values aligned left)
```csharp
AlignmentGetter = (v)=>v is double d ? d < 0 ? TextAlignment.Right : TextAlignment.Left:
								// not a double e.g. could be DBNull.Value
								TextAlignment.Left
```

For formatting theres a delegate too... although that might be overkill, a simple string property `Format` might be better if I can work out a way to do that.

```csharp
var dateFormatStyle = new ColumnStyle() {
				Alignment = TextAlignment.Right,
				RepresentationGetter = (v)=> v is DateTime d ? d.ToString("yyyy-MM-dd"):v.ToString()
};
```

You can also specify maximum and minimum widths for cols in the `ColumnStyle` class

**Comment by dynamoRando** [comment]
Just wanted to say that this is great and have started used it. Appreciate the contribution! I have the class manually added to my code, looking forward to when this is merged!

Have a great day!

**Comment by tznind** [comment]
I have added mouse support to table view

- Clicking a cell selects the cell
- Mouse wheel scrolls up/down 

Not sure if there is a way to tell if the Shift key is down in which case Shift Mouse Wheel could do horizontal scrolling.

table-view-mouse

**Comment by BDisp** [comment]
Very great job, many thanks. You can see the `ScrollView `sample where it deals with `WheeledLeft `and `WheeledRight `flags.
It's possible to select to entire line? It will be nicer. It also be nicer on double click will edit the cell like F3 does.

**Comment by tznind** [comment]
FullRowSelect makes sense but would make horizontal scrolling with keyboard alone a challenge.  Currently when you move the selected cell using the arrow keys the scroll area updates when it moves off the current scroll area (like a spreadsheet does).

With full row selection though there is no horizontal 'current cell'... I guess the simplest way would be to make full row select still include a single 'active cell' sort of like this:

image

**Comment by BDisp** [comment]
That's would be nice too. Thanks.

**Comment by tznind** [comment]
Ok have added FullRowSelect property (defaults to false).  I implemented `PositionCursor` so the selected cell always has the cursor in it.  This should ensure the user can tell which cell is the 'active' one within the row even when the whole row is selected.

image

**Comment by BDisp** [comment]
Fantastic you are awesome. Thanks.

**Comment by tznind** [comment]
I have added multi selection (Shift + arrow/home/end key):

multi-select

Is there a way to tell if the Shift/Ctrl key are down during mouse activities e.g. click one cell and ctrl click another.

**Comment by BDisp** [comment]
> Is there a way to tell if the Shift/Ctrl key are down during mouse activities e.g. click one cell and ctrl click another.

You have to check for the `MouseFlags.ButtonShift` and `MouseFlags.ButtonCtrl`. Unfortunately in `Linux `doesn't not work as well as in `Windows`.

**Comment by BDisp** [comment]
I forgot to mention that I dealed with `MouseFlags.ButtonShift` and `MouseFlags.ButtonCtrl` a long time ago in the `FileDialog.cs` at the `MouseEvent `method on `DirListView `class.

**Comment by tig** [comment]
Like TreeView, I feel like we need a good collection of use-cases coded up before merging a big new control like this.

The more there are, the more confidence we all will have that something fundamental has not been missed in the design/API.

What are the current samples that have been written?

**Comment by tznind** [comment]
Thanks for the guidance @tig

I have added a simple CSV editor use case to the Scenarios.  Given there are entire libraries around parsing / saving CSV data I've not tried to handle newlines, escaping etc.  I'm assuming the idea is primarily demo the control and how to do common tasks with it.

csvExample

I've also added an article to the docs on common use cases and how to get a DataTable for them:

https://github.com/tznind/gui.cs/blob/table-view/docfx/articles/tableview.md

Let me know if this is the right way to go and I can expand on the docs to cover common tasks, limitations etc.

**Comment by BDisp** [comment]
Impressive. Is it possible to move a column or row to another location?

**Comment by tznind** [comment]
> Impressive. Is it possible to move a column or row to another location?

Thanks, yes you can do most things with `DataTable` since it is a core class of C# - it is pretty versatile.  I've added moving rows and sorting to the example.  All these operations (sort, reorder) change the `System.DataTable` data directly.

The only 'view' level manipulations I've implemented so far are the `Format` and `MaxLength` etc fields in `TableStyle`.  You can see if you put a Format on a column it only affects the presentation layer not the value stored (so you can change the Format later on if you want).

**Comment by migueldeicaza** [comment]
This is outstanding!   Thanks for this beautiful work!

**Comment by tig** [comment]
I *finally* got a chance to test and play with this. Thank you!!!!

**Comment by dynamoRando** [comment]
Awesome stuff!

**Comment by lzanoni-stm** [comment]
Is there a way to remove the selected style when the focus leaves the TableView  (and put it back when entering)?

**Comment by lzanoni-stm** [comment]
Thanks for the blazing fast reply and example :)

Sorry, I probably haven't used the right words: what I'd like is that, when losing focus, the currently selected cell becomes normal (without the highlight), without altering the rest of the table.

**Comment by tznind** [comment]
Good point.  I have a prototype fix in #1776  please can you write this as a new issue so that it is easier to find and not mixed in with this old PR?

**Pull request merged**
