### PR TITLE
Modernize and simplify example project configuration files

### PR DESCRIPTION
**Pull request by pviotti**
- modernizes and simplifies the Designer and Example project files (adopting the [SDK-style](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj) dotnet project [format](https://www.hanselman.com/blog/UpgradingAnExistingNETProjectFilesToTheLeanNewCSPROJFormatFromNETCore.aspx))
 - updates the version of Terminal.Gui used by the example projects (StandaloneExample, FSharpExample)

**Why**
I could not build the whole solution using dotnet CLI or Visual Studio 2017 or 2019, because the projects were targeting different frameworks, and there were duplicate references and other cruft.  
With these changes should also be easier to maintain the CI/CD and release pipelines.

**Details**
 - since the target of this library is .NET Framework 4.6.1 and .NET Standard 2.0 (e.g. .NET Core 2.0), the example projects now target such frameworks
 - the solution file has been re-created too. It works for VS 15+ (VS 2017+)

### CODE REVIEW

**Comment by migueldeicaza** [comment]
This breaks the Mac build.

**Comment by pviotti** [comment]
Some odd packet signing errors indeed. It looks like this issue with the nuget authentication cache https://github.com/NuGet/docs.microsoft.com-nuget/issues/1401 I'll try upgrading the dotnet sdk from 2.1.4 to 2.1.5.

**Comment by pviotti** [comment]
looks like the problem with the broken build was in the default `install` step in Travis, so I set it to be skipped since it's duplicate `nuget restore` anyway.

**Comment by BDisp** [comment]
@pviotti how did you configure the build to avoid the errors in the pull request?

**Comment by BDisp** [comment]
> 
> 
> @pviotti how did you configure the build to avoid the errors in the pull request?

Silly question, sorry.

**Comment by migueldeicaza** [comment]
Could you rebase to study the changes?

**Comment by pviotti** [comment]
> Could you rebase to study the changes?

Done.

**Comment by pviotti** [comment]
Closing since now the solution builds with VS19 and the dotnet cli.

**Pull request closed without merging**
