### PR TITLE
All my pull-request at once

### PR DESCRIPTION
**Pull request by BDisp**

### CODE REVIEW

**Comment by BDisp** [comment]
Dragging is already working by press on the top of the window. Enjoy it :) 
@migueldeicaza maybe this is my last commit for this pr. I will start submitting pr's into smaller branches. So I will close and delete the others pr's within 2 or 3 days, unless you say otherwise.

drag

**Comment by migueldeicaza** [comment]
Hello,

Thanks for this massive patch - I have done a quick review, and I think that given the volume of this patch and the long times it takes me to review, that I will take it, and if there are issues, I will fix those later on.

I would if you could do the following changes before I merge:

* Please drop the use of `private` in the source code.
* For any new public member that is not an override, please provide API documentation
* For new types that introduce new keyboard or mouse behavior, please add that to the documentation.
* There are a couple of API methods that I pointed out that I would love to see renamed (SelText for example).

Those are mostly style changes as you can see, I have no objections to the substance.

Feel free to ping me on twitter, if I do not reply quickly here, my GitHub notifications are a mess, and I have given up on trying to keep up with them.

**Comment by BDisp** [comment]
2 errors:
The missing file is ../packages/NETStandard.Library.2.0.3/build/netstandard2.0/NETStandard.Library.targets.

**Comment by migueldeicaza** [comment]
Any ideas how I can fix the build failure, as it complains about that missing file?

**Comment by BDisp** [comment]
@migueldeicaza , if it's needed to change something in the PR please let me know.

**Comment by BDisp** [comment]
Design and Example projects are pointing NStack to an empty netstandard folder in Object Browser.

netstandard

**Comment by BDisp** [comment]
I was wrong, sorry. It's reference C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\netstandard.dll.
What's is hap it's always I uninstall and reinstall NStack, nuget notify that the netstandard of the Design and Example projects uses version 1.6 and even update to the 2.0.3, travis give the error. Now with the NStack version 0.14 my Travis passed only with conflits as posted here. But in Gui.cs repo travis report a error yet.

travis

**Comment by migueldeicaza** [comment]
Alexander Köplinger said:

> if you use ValueTuple then bump your TargetFramework to net47 and get rid of the nuget package

**Comment by BDisp** [comment]
My last Travis job log:

```
    598 Warning(s)
    0 Error(s)
Time Elapsed 00:00:11.51
The command "msbuild /p:Configuration=Release Terminal.sln" exited with 0.
Done. Your build exited with 0.
```

**Comment by migueldeicaza** [comment]
I think we need to remove this line:

```
<package id=“System.ValueTuple” version=“4.5.0" targetFramework=“net461” />
```

And bump the target framework version on the affected csproj files to `net47`

**Comment by BDisp** [comment]
> I think we need to remove this line:
> 
> ```
> <package id=“System.ValueTuple” version=“4.5.0" targetFramework=“net461” />
> ```
> 
> And bump the target framework version on the affected csproj files to `net47`

That's already done :)

**Comment by migueldeicaza** [comment]
Merged the pull request - and will sort out any fall out in the main branch.

**Comment by BDisp** [comment]
> 
> 
> Merged the pull request - and will sort out any fall out in the main branch.

You may need to fix it in Mono:

The reference assemblies for framework ".NETFramework,Version=v4.7.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/runner/runners/2.165.2/work/1/s/Designer/Designer.csproj]

**Pull request merged**
