### PR TITLE
Removed redundant properties on MenuBar View

### PR DESCRIPTION
**Pull request by KDERazorback**
*This commit is intended to make some refactoring on the MenuBar View, to make it more consistent and intuitive, and to remove redundant members in order to improve code maintenance and usability.*

Currently, the `MenuBar` view has two members for storing opposite states for the "Is Menu Open?" logical question. Those members are: `isMenuClosed` and `MenuOpen`. The second storing the negated value of the first, but without any automatic logic handling implemented. This means that in any point in time those two members could become desync and introduce bugs to the View, also code maintainability suffers by requiring to update two internal states with opposite logic values each time the Menu states changes.

Consider applying this commit to enhance the usability and code maintenance on the `MenuBar` view.

- Redundant members `isMenuClosed` and `MenuOpen` were replaced with a more consistent and intuitive single `IsMenuOpen` property.
- `CloseMenu` method is now Public.
- `StartMenu` has been renamed to `OpenMenu` and made Public.
+ Added missing XmlDoc to `OpenMenu` and `CloseMenu`, and fixed an small typo to `MenuOpen/IsMenuOpen`.

**Warning: This commit breaks compatibility with previous versions.**

**Changes required to host apps:**

`MenuBar.MenuOpen` property renamed to `IsMenuOpen`
`MenuBar.StartMenu` method renamed to `OpenMenu`, use it to open the Menu
Use `MenuBar.CloseMenu` to close the active menu.

### CODE REVIEW

**Comment by tig** [comment]
In addition to the conflict, I'm about to accept the doc update PR and it's likely going to cause you to need to rebase this. So hold tight...

**Comment by tig** [comment]
@KDERazorback you can now resolve the conflicts by pulling the latest master and rebasing. 

Can you also ensure Example and UI Catalog are updated to reflect your API changes?

Once you do that I'll accept this.

**Comment by KDERazorback** [comment]
Sure, will get into it in a minute. Thanks.

**Comment by KDERazorback** [comment]
Done. No changes are required to the Designer project since the `MenuBar` view is not being manipulated programatically. 

But in the meantime, i found a bug in the Key event handling code of `View` that triggers a library crash. This happens when the Subviews for a currently active view are updated from within any Key event subscriber. This has been fixed with the addition of a new `Handled` property to the `KeyEventEventArgs` that forces the `foreach` block inside the Key handling methods of the `View` (such as KeyDown, KeyUp, etc). to stop notifying further event subscribers once the Keystroke is marked as Handled.

*Note: Host applications should be updated to properly toggle the `Handled` property when the View's tree is updated, like when Opening/Closing a menu, or adding/removing child Views. Otherwise an `InvalidOperationException` with message "Collection was modified; enumeration operation may not execute" could be thrown by the View.*

The `Example` project has been updated to expose the new feature, the `MenuBar` can be toggled Open/Closed when pressing `Ctrl+T` too.

**Changes (from commit text):**
+ Added `Handled` property of type bool to the `KeyEventEventArgs` class.
+ Added ability to stop further propagation for already handled events on Views for Keyboard related event subscribers (like `KeyDown`, `KeyUp` and `KeyPress`). The driver will check the `Handled` property of the `KeyEventEventArgs` passed to the subscribers and will stop any further invocations when its found true.
+ Updated `Example` project to expose the ability to programatically Open/Close a `MenuBar` from custom keystrokes.

This branch is ready to be merged.

**Comment by BDisp** [comment]
Very good choice of `Handled`. It was really missing a lot. I had to go around a lot to avoid the error `"Collection was modified; enumeration operation may not execute"` and so it gets really clean.

**Comment by tig** [comment]
Can you rebase sot that 266 files aren't changed? Please.

**Comment by KDERazorback** [comment]
All done. All checks passed and rebased to f25469d08f0dbc6c0dba9a3428a7bfccb4e496e7

**Comment by tig** [comment]
Fantastic!

**Pull request merged**
