### PR TITLE
ComboBox render fix at dialog after close listview.

### PR DESCRIPTION
**Pull request by lzylinl**
Seems this right way

### CODE REVIEW

**Comment by tig** [comment]
@BDisp - do agree this is a good fix?

**Comment by BDisp** [comment]
I'll see and then I'll give feedback

**Comment by BDisp** [comment]
It seems that this does not influence anything but as @fergusonr  submitted a PR earlier, maybe it would be better for him to comment, please.

**Comment by fergusonr** [comment]
This PR has no effect. @lzylinl is there a specific issue this fixes?

**Comment by lzylinl** [comment]
Look at this issue https://github.com/migueldeicaza/gui.cs/issues/816
Use same code for reproduce.
If we open and close combobox (not select anything) we can see this
Wew72V3
Area from listbox does not cleared after combo closed

**Comment by BDisp** [comment]
Ok. @tig I confirm that this PR fixes the issue #816.

**Comment by fergusonr** [comment]
Thankyou both @lzylinl  @BDisp

**Comment by tig** [comment]
nicely done folks.

**Pull request merged**
