### PR TITLE
Timefield format with bounds values

### PR DESCRIPTION
**Pull request by BDisp**
Uses 0-24H format and implemented lower and upper bounds to TimeField

### CODE REVIEW

**Comment by kbilsted** [comment]
Not sure what problem you are trying to solve ?

**Comment by BDisp** [comment]
@kbilsted you are right, in which case we should also use sepChar in the format. Thanks.

**Comment by kbilsted** [comment]
`sepChar` is a strange name for a `string` variable.  But more imporantly Not sure what problem you are trying to solve ? Why not trust the standard parser ?

**Comment by BDisp** [comment]
@kbilsted sepChar can be interpreted as a separator character and not as a Char type. I think it is safer to use the culture info derived separator than to use only the standard parser and also when using boundary checking. Anyway, coding has many different ways to achieve the same goal, depending on one's perspective :)

**Comment by BDisp** [comment]
@kbilsted with this commit you will understand why the sepChar variable was declared as char :)

**Comment by kbilsted** [comment]
Not sure what problem you are trying to solve ? Why not trust the standard parser ?

I Think it ia better to use the full string not just the first char. Some locales may define sevetal chars as separator

**Comment by BDisp** [comment]
@kbilsted in my commit I commented that you would realize why it was declared as char. Is that this change forced me to change the checking of the statements like if (Text [CursorPosition] == ':')
to if (Text [CursorPosition] == sepChar.ToCharArray () [0]). Perhaps this is why it was originally in the repository declared as char to make it easier to verify. However, there is nothing wrong with your observation.

**Comment by kbilsted** [comment]
Your can compare using `string.StartsWith()` and provide an index

**Comment by BDisp** [comment]
@kbilsted does not work because Text is a ustring that contains the ascii character code and not a string. To compare we have to convert to string in case of ustring or convert to char in case of string, which is what I did. As there has to always be this conversion the original author decided to declare the separator as char and I think it should continue like this, so I do not take the PR not to be accepted. But, however, there is an important comparison because I am comparing with the separator variable instead of the literal character ':'

**Comment by migueldeicaza** [comment]
Fantastic patch - thank you for your contribution!

**Pull request merged**
