### PR TITLE
Fixes #1529 - Mdi container will deal with the visibility of their child's.

### LINKED ISSUE #1529: Mdi container won't repaint when the visibility of the child is changed
Minimal reproducible example:

```cs
var top = new Toplevel
{
	IsMdiContainer = true
};

var sb = new StatusBar(new[]
{
	new StatusItem(Key.A, "~A~ New child", () =>
	{
		var child = new Window("Test")
		{
			X = Pos.Center(),
			Y = Pos.Center(),
			Height = 20,
			Width = 20
		};
		var hide = new Button("Hide");
		hide.Clicked += () =>
		{
			child.Visible = false;
		};
		child.Add(hide);
		Application.Run(child);
	})
});
top.Add(sb);

Application.Run(top);

```

1. Click on Add new child in the Status bar
image
2. Click on the Hide button in the child
3. The content of the Child is hidden, but the Child window stays until a new Child is added
image

### PR DESCRIPTION
**Pull request by BDisp**

### CODE REVIEW

**Comment by BDisp** [comment]
I already run the unit tests on `Windows` and on `Linux` without any errors. So I think it's a false result.

**Review by tig — CHANGES_REQUESTED** [review]
This builds, runs, and tests fine when I bring the PR down locally, but I can't merge it until we figure out why it's failing on CI/CD.

I tried re-running it on github and it failed again.

**Comment by BDisp** [comment]
I'll take a look, thanks.

**Comment by BDisp** [comment]
I only did a rebase and sync to github and it not give any error checks. Also bellow a test in the Dev Container.

codespace

**Review by tig — APPROVED** [review]

**Comment by tig** [comment]
It's still not succeeding in the Action. I don't see any obvious reason! Weird.

**Comment by BDisp** [comment]
If I get the error I would try to fix, but I've got nothing.

**Comment by tig** [comment]
If you run the Action on your own repo, does it succeed?

**Comment by BDisp** [comment]
Do you mean in .decontainer?

**Comment by tig** [comment]
> Do you mean in .decontainer?

No, I mean when you push this PR to https://github.com/BDisp/gui.cs/tree/mdi-visible-fix does the Build Action run and succeed?

**Comment by BDisp** [comment]
Yes, normally I receive an email reporting the failed build and I didn't.

**Comment by tig** [comment]
```
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:04.41]     Terminal.Gui.ScenarioTests.Run_All_Scenarios [FAIL]
  Failed Terminal.Gui.ScenarioTests.Run_All_Scenarios [1 s]
  Error Message:
   Assert.Equal() Failure
Expected: 0
Actual:   1
  Stack Trace:
     at Terminal.Gui.ScenarioTests.Run_All_Scenarios() in /home/runner/work/gui.cs/gui.cs/UnitTests/ScenarioTests.cs:line 87

```

This is the test that's failing:

image


It seems there is an issue with your PR and `Init` within the environment provided by the build Action.

**Comment by BDisp** [comment]
I'll check again asap.

**Comment by tig** [comment]
BTW, you can get the info I got by clicking Details on the failed Action:

image

**Comment by BDisp** [comment]
@tig all test passed now. So I think it not giving any problem now.

pull-request-1531

**Pull request merged**
