### PR TITLE
TableView - adds last column dividing line

### PR DESCRIPTION
**Pull request by tznind**
There are a couple of issues I need to iron out (see demo) and a unit test to add but is this a suitable fix for #1286 ?

table-last-column

### CODE REVIEW

**Comment by BDisp** [comment]
But with an option if the last column width is not set, then it fill all the available width.

**Comment by tig** [comment]
This meets my needs.

**Comment by tznind** [comment]
Ok cool I will try to work out the issues and make it only behave this way when there is a `MaxLength` set but it might take me a few days to get to this.

**Comment by tznind** [comment]
So MaxWidth is an `int` so always has a value (it also has a configurable default).  Rather than change this or impose some arbitrary logic I have just added a style setting `EnforceMaxWidthOnLastColumn`:

I have also added tests.  In the interests of 'no surprises' backwards compatibility I have left it as default false (do not have the last column).  If you think this should instead default to true let me know and I can change that.

enforceMaxWidth
_Toggling EnforceMaxWidthOnLastColumn in the TableEditor scenario in UICatalog_

**Comment by BDisp** [comment]
How about if `MaxWidth` is equal to `-1` then the column is hidden, if equal to `0` (zero), automatically sets the `EnforceMaxWidthOnLastColumn` to true.

**Comment by tznind** [comment]
So the way the table view works is:

- Take y rows of data (scroll offset + height - space taken by headers)
- Calculate width of first column (maximum width of the content of those rows)
   - Enforce MinWidth
   - Enforce MaxWidth
- If there is space for the column add it to the list of columns that will be rendered

This has several advantages
- As you scroll down a large table the columns auto resize to allow the content to fit
- We don't have to resolve the entire table into text in order to render it

So I'm not sure `MaxWidth` is exactly related to this last column feature.  Given that with small content the last column is going to be less width than `MaxWidth` anyway.

Maybe It would be better to rename this Style setting `Style.ExpandLastColumn`? (certainly that is a better name than `EnforceMaxWidthOnLastColumn` now I think about it).

**Comment by tznind** [comment]
> Just a question, can it have a hidden column?
> 
> Thanks for your efforts.

Not in the `TableView` API.  But you can use `System.DataTable.RemoveColumn(DataColumn col)` to take a column out and you can add it back in again with `System.DataTable.AddColumn(DataColumn col)`.  So it would be very easy for the API user to keep a list of removed ones and simulate hiding/showing columns.

**Comment by BDisp** [comment]
Understood. Many thanks @tznind :-)

**Comment by BDisp** [comment]
> Well, that depends. If `EnforceMaxWidthOnLastColumn` can be used by any` Style`, it can also cover other styles.

Sorry @tznind, my bad. `EnforceMaxWidthOnLastColumn` already belong to `Style`. I failed that.

**Review by tig — APPROVED** [review]
Love.

**Pull request merged**
