### PR TITLE
Windows: Implementing mouse events and writing to console buffers

### PR DESCRIPTION
**Pull request by nickvdyck**
This is a first initial implementation of making mouse events work on windows. Related to #67 although this does not solve the resizing issues.

It still pretty rough at the moment, just wondering what you think. It is built upon the initial work that was already in place, just had to wire some bits up.

Currently tested on .net core 2.1.0.rc1 and full framework 471.
Also verified that I didn't break any unix stuff. Ubuntu 16.04 dotnet core 2.1.0.rc1 and mono 5.10.
Don't have a mac, so haven't tested that one. But given that the changes or isolated to the windowsdriver this should be fairly safe. 😁 (famous last words)

### CODE REVIEW

**Comment by nickvdyck** [comment]
Thanks,

I like what you did with reshuffling those drivers around. I rebased this branch on top of master.

**Comment by migueldeicaza** [comment]
Wow - this is amazing!   This is exactly what I wanted to do!

I came down to my office tonight to start reading documentation on the screen buffer and decided to check on where this pull request was.

The issue with the cursor should be fixable by implementing the UpdateCursor method by calling [SetConsoleCursorPosition](https://docs.microsoft.com/en-us/windows/console/setconsolecursorposition).

Can you tell me more about the mouse events not working?

Finally, before I merge, just as a sanity check, could you state on this commit that the code is MIT licensed?   Then I can go ahead and merge.

**Comment by nickvdyck** [comment]
I fixed the cursor positioning by implementing the `UpdateScreen` method just like you said. Didn't realize it was that easy 🤦‍♂️, thanks for pointing me the right direction.

The basic implementation for mouse events is working. But I did notice that when clicking on the checkbox it checks it but than also immediately unchecks the control. I haven't really looked in to this so am not really sure what is happening here.

I'll see if I can find some time later today to do some debugging.

I also added an MIT license to the top of the file. I'm not really familiar with licensing so I'm not sure this is what you meant.

**Comment by migueldeicaza** [comment]
Fabulous news!   Going to merge this now.

Thanks!

**Pull request merged**
