### PR TITLE
Trying updating FSharpExample to net5.0

### PR DESCRIPTION
**Pull request by BDisp**
@En3Tho can you help to fix the errors on this PR, please.

### CODE REVIEW

**Comment by En3Tho** [comment]
@BDisp Yea, sure. Sorry for not responding earlier - it was a night already.

**Comment by En3Tho** [comment]
How do I make a PR to your branch? 
image
GitHub gives me this...

**Comment by En3Tho** [comment]
Maybe you can pull changes from https://github.com/En3Tho/gui.cs/tree/fsharp-example-build-fix ?

Basically new overloads had destroyed type-inference/overload-resolution of F# compiler. The fix was to manually upcast objects. 

Note that with F#6 some of the upcasts will go away as F# is going to be little bit impicit-cast friendly (although I do not think that this is always a good thing). Coming from C# this maybe feels boilerplaitish but F# stood for explcitness for a long time a I hope it will continue doing so.

**Comment by BDisp** [comment]
> I've created a pull request #1481
> Maybe we can merge it and close this one?

Thanks a lot @En3Tho. I already have pushed the fix while you submitted your PR, sorry. Please check if it's alright. Case affirmative you can close your PR. I already tried this approach but I was casting in each array element or after the `MenuBarItem`, but not on all of them.

**Comment by BDisp** [comment]
@En3Tho is this issue solved (https://github.com/migueldeicaza/gui.cs/issues/1470#issuecomment-929579523)?

**Pull request merged**
