### PR TITLE
Added support for coloring cells in TableView

### LINKED ISSUE #1356: TableView cell color
Hey,

Is there a way to change the color of certain cells in a table view based on their value? Is there any other customization possible othen than through the RepresentationGetter?

Thanks,
Marcel

### PR DESCRIPTION
**Pull request by tznind**
Fixes #1356

red

### CODE REVIEW

**Comment by tznind** [comment]
Do we want the ability to color the whole row as well as individual cell values?

**Comment by tznind** [comment]
I've added alternating colors to the example and row color support.

alternating

But I have noticed that we have lost the ability to tell which cell is the 'last/active selected cell' in a multi cell selection.  I need to look into when that happened but I see the issue is in main too so it is not an effect of this PR.

**Comment by tznind** [comment]
I've made the parameters to the color getter delegates into classes to allow adding new 'parameters' without causing a breaking change in the API and because it makes implementing them easier and the resultant code more readable.

previously:
```csharp
tableView.Style.RowColorGetter = (i,r)=> {return i%2==0 ? alternatingColorScheme : null;};

colStyle.ColorGetter = (i,v)=>v is double d ? 
			// color 0 and negative values red
			d <= 0.0000001 ? i%2==0 && miAlternatingColors.Checked ? redColorSchemeAlt: redColorScheme : 
			// use normal scheme for positive values
			null:
			// not a double
			null
```
now:
```csharp
tableView.Style.RowColorGetter = (a)=> {return a.RowIndex%2==0 ? alternatingColorScheme : null;};

colStyle.ColorGetter = (a)=> a.CellValue is double d ? 
			// color 0 and negative values red
			d <= 0.0000001 ? a.RowIndex%2==0 && miAlternatingColors.Checked ? redColorSchemeAlt: redColorScheme : 
			// use normal scheme for positive values
			null:
			// not a double
			null
```

The color delegates (`RowColorGetterDelegate` and `CellColorGetterDelegate`) return a `ColorScheme` i.e. render the cell using these colors.  So out of the box the control doesn't support mutli coloured cells.  But I've also made `RenderCell` virtual so that you can override it to do truly wild coloring if you really want:

image

**Comment by tznind** [comment]
Just noticed there are a lot of whitespace changes in TableView, possibly a visual studio layout thing? want me to try and rebase this ignoring whitespace @tig ?

**Review by tig — APPROVED** [review]
This is awesome.

**Comment by tig** [comment]
> Just noticed there are a lot of whitespace changes in TableView, possibly a visual studio layout thing? want me to try and rebase this ignoring whitespace @tig ?
> 
> I think the whitespace change is following the visual studio settings for the repo. You can hide the whitespace changes when reviewing or I can try to rebase to revert them:
> 
> image

I was able to get through it ok (before seeing your not on how to hide them!). All good.

**Pull request merged**
