### PR TITLE
Some improvements in menu and listview

### PR DESCRIPTION
**Pull request by BDisp**
Allowing menu navigation with mouse and check and uncheck listview with mouse

### CODE REVIEW

**Comment by migueldeicaza** [comment]
Hello,

While I love the contribution, this looks like a massive set of changes.

Would it be possible to submit the different features independently?

**Comment by BDisp** [comment]
Hi, I'm glad you appreciated my contribution. I really should have submitted the changes in separate branches but it was due to lack of experience with git. If you ask to send separately the features that I implemented is that it should be possible to make this separation and I will investigate. There are still some features that do not work in mono but work well in windows, such as text selection via mouse, cut, copy and paste. Which advises me to debug the code in linux since it is not a system that dominates much, especially at the development level. If so do you think I should close this pr?

**Comment by kbilsted** [comment]
@BDisp  the more commits the harder it will get to have the PR merged, I suggest you do each feature in a separate PR

**Comment by BDisp** [comment]
For example, I created two branches for the last two PRs I submitted but still comes together with all the commits I have done. I confess I don't have much experience using GIT but I haven't figured out how to separate the new commits without dragging all the previous ones. Anyway ...

**Comment by biohazard999** [comment]
@BDisp https://www.atlassian.com/git/tutorials
You should checkout the latest commit from @migueldeicaza first, then create the branch.
I assume you created the branch from your current branch. be sure to checkout master first, then create a branch, afterwards make your changes, push them and make a new PR

**Comment by BDisp** [comment]
@biohazard999 I actually created new branches from my current branch and didn't think I should checkout from @migueldeicaza first. Thank you so much for your precious explanation.

**Comment by BDisp** [comment]
I'll submit a new one

**Comment by biohazard999** [comment]
@bdisp you are Welcome!

**Pull request closed without merging**
