### PR TITLE
Added DateField view

### PR DESCRIPTION
**Pull request by BarryNolte**
Created DateField control as per issue #13

### CODE REVIEW

**Comment by migueldeicaza** [comment]
Thanks for the contribution!    How does this cope with formats in different locales?   For example, outside of the US the dates are usually DD/MM/YYYY

**Comment by BarryNolte** [comment]
Aaarrggg... I should have caught that.  I'll fix it.

**Comment by migueldeicaza** [comment]
@BDisp Do we still need this patch with your mega-patch merged? 

Can I clsoe this issue?

**Comment by BDisp** [comment]
Yes you can close.

**Pull request closed without merging**
